"""Optimization algorithms admitted after the contraction gate."""

from .agp_subspace import (
    GeneralizedEigenResult,
    OverlapWhitening,
    TermPruningAssessment,
    assess_term_pruning,
    contribution_gram_spectrum,
    leave_one_out_energies,
    overlap_whitening,
    solve_generalized_hermitian,
)
from .finite_agp_training import (
    FiniteAgpConfig,
    canonical_pair_matrices,
    run_finite_agp_variable_projection,
)
from .pfaffian_training import (
    FactorizedPairConfig,
    PfaffianPairConfig,
    run_factorized_pfaffian_pair,
    run_pfaffian_pair,
)
from .diagonal_path_training import (
    DiagonalPathConfig,
    canonical_slater_orbitals,
    embed_diagonal_path_orbitals,
    extend_diagonal_path_terms,
    run_diagonal_path_variable_projection,
)
from .diagonal_path_growth import (
    AdaptiveTermCandidate,
    AdaptiveTermGrowth,
    select_adaptive_diagonal_path_term,
)
from .diagonal_path_contract import (
    DIAGONAL_PATH_CHECKPOINT_SCHEMA_VERSION,
    DIAGONAL_PATH_RESULT_SCHEMA_VERSION,
    load_diagonal_path_checkpoint,
    validate_diagonal_path_checkpoint,
    validate_diagonal_path_result,
)
from .adaptive_diagonal_path_contract import (
    ADAPTIVE_DIAGONAL_PATH_CHECKPOINT_SCHEMA_VERSION,
    ADAPTIVE_DIAGONAL_PATH_RESULT_SCHEMA_VERSION,
    load_adaptive_diagonal_path_checkpoint,
    validate_adaptive_diagonal_path_checkpoint,
    validate_adaptive_diagonal_path_result,
)
from .adaptive_diagonal_path_training import (
    AdaptiveDiagonalPathConfig,
    AdaptiveDiagonalPathStageConfig,
    run_bounded_adaptive_diagonal_path,
)
from .slater_source_contract import (
    SLATER_SOURCE_CHECKPOINT_SCHEMA_VERSION,
    SLATER_SOURCE_METHOD,
    SLATER_SOURCE_RESULT_SCHEMA_VERSION,
    load_slater_source_checkpoint,
    validate_slater_source_checkpoint,
    validate_slater_source_result,
)
from .slater_source_training import (
    SlaterSourceOptimizerConfig,
    SlaterSourceSolverConfig,
    canonical_lowest_slater,
    load_slater_source_command_config,
    run_slater_source_adaptive_solver,
    slater_source_config_from_record,
)
from .correlated_exterior import (
    CorrelatedExteriorConfig,
    CorrelatedTwoFermionResult,
    canonical_two_orbital_carrier,
    correlated_two_fermion_observables,
    gauss_hermite_rule,
    harmonic_function_values,
    harmonic_function_values_and_derivatives,
    initial_two_orbital_carrier,
    project_correlated_two_fermion_coefficients,
    run_correlated_exterior_optimization,
)

__all__ = [
    "GeneralizedEigenResult",
    "OverlapWhitening",
    "TermPruningAssessment",
    "assess_term_pruning",
    "contribution_gram_spectrum",
    "leave_one_out_energies",
    "overlap_whitening",
    "solve_generalized_hermitian",
    "FiniteAgpConfig",
    "canonical_pair_matrices",
    "run_finite_agp_variable_projection",
    "FactorizedPairConfig",
    "PfaffianPairConfig",
    "run_factorized_pfaffian_pair",
    "run_pfaffian_pair",
    "DiagonalPathConfig",
    "canonical_slater_orbitals",
    "embed_diagonal_path_orbitals",
    "extend_diagonal_path_terms",
    "run_diagonal_path_variable_projection",
    "AdaptiveTermCandidate",
    "AdaptiveTermGrowth",
    "select_adaptive_diagonal_path_term",
    "DIAGONAL_PATH_CHECKPOINT_SCHEMA_VERSION",
    "DIAGONAL_PATH_RESULT_SCHEMA_VERSION",
    "load_diagonal_path_checkpoint",
    "validate_diagonal_path_checkpoint",
    "validate_diagonal_path_result",
    "ADAPTIVE_DIAGONAL_PATH_CHECKPOINT_SCHEMA_VERSION",
    "ADAPTIVE_DIAGONAL_PATH_RESULT_SCHEMA_VERSION",
    "load_adaptive_diagonal_path_checkpoint",
    "validate_adaptive_diagonal_path_checkpoint",
    "validate_adaptive_diagonal_path_result",
    "AdaptiveDiagonalPathConfig",
    "AdaptiveDiagonalPathStageConfig",
    "run_bounded_adaptive_diagonal_path",
    "SLATER_SOURCE_CHECKPOINT_SCHEMA_VERSION",
    "SLATER_SOURCE_METHOD",
    "SLATER_SOURCE_RESULT_SCHEMA_VERSION",
    "SlaterSourceOptimizerConfig",
    "SlaterSourceSolverConfig",
    "canonical_lowest_slater",
    "load_slater_source_checkpoint",
    "load_slater_source_command_config",
    "run_slater_source_adaptive_solver",
    "slater_source_config_from_record",
    "validate_slater_source_checkpoint",
    "validate_slater_source_result",
    "CorrelatedExteriorConfig",
    "CorrelatedTwoFermionResult",
    "canonical_two_orbital_carrier",
    "correlated_two_fermion_observables",
    "gauss_hermite_rule",
    "harmonic_function_values",
    "harmonic_function_values_and_derivatives",
    "initial_two_orbital_carrier",
    "project_correlated_two_fermion_coefficients",
    "run_correlated_exterior_optimization",
]
